version: "3.9"

services:
  db:
    image: postgres:16
    container_name: boncoeur-postgres
    restart: always
    environment:
      POSTGRES_USER: boncoeur
      POSTGRES_PASSWORD: boncoeur
      POSTGRES_DB: boncoeur
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: boncoeur-pgadmin
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@boncoeur.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: